server:
  port: 8080
  servlet:
    context-path: /test

spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gitai?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: query

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
logging:
  config: classpath:logback.xml


quartz:
  gitlab:
    project:
      user:
        brunch:
          cron:
            expression: 0 50 03 * * ?
